# Spring Config
spring:
  datasource:
    url: jdbc:mysql://localhost/medida
    username: root
    password:

    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

  # Jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

# Server port
server:
  port: 8080

# Log file
logging:
  file: app.log